# Kickbase Ultimate Analyzer - Konfiguration
# Alle Einstellungen f체r das Tool

# Basis-Konfiguration
app_name: "Kickbase Ultimate Analyzer"
version: "1.0.0"
debug: false

# Daten-Verzeichnisse
directories:
  data: "kickbase_data"
  exports: "exports"
  logs: "logs"
  cache: "cache"
  temp: "temp"

# Machine Learning Einstellungen
machine_learning:
  test_size: 0.2
  random_state: 42
  n_estimators: 100
  cv_folds: 5
  
  # Modell-Parameter
  models:
    random_forest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 5
    
    xgboost:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
    
    lightgbm:
      n_estimators: 100
      learning_rate: 0.1
      num_leaves: 31

# API-Einstellungen
api:
  kickbase:
    rate_limit_delay: 0.1  # Sekunden zwischen Requests
    max_retries: 3
    timeout: 30
  
  external:
    weather_api_key: ""
    betting_api_key: ""
    bundesliga_api_key: ""

# Datensammlung
data_collection:
  enable_player_stats: true
  enable_market_history: true
  enable_match_data: true
  enable_weather_data: true
  enable_betting_odds: true
  
  # Limits f체r Demo/Testing
  max_players_demo: 50
  max_history_days: 365

# Export-Einstellungen
export:
  formats: ["json", "csv", "excel", "html", "markdown"]
  include_raw_data: true
  compress_files: false

# Cloud-Integration
cloud:
  enabled: true
  default_bucket: "kickbase-analysis"
  auto_upload: true
  
  google_cloud:
    enabled: false
    project_id: ""
  
  aws:
    enabled: false
    region: "eu-central-1"

# AI-Integration
ai:
  enabled: true
  default_provider: "openai"
  
  openai:
    model: "gpt-4"
    max_tokens: 1500
    temperature: 0.7
  
  anthropic:
    model: "claude-3-sonnet-20240229"
    max_tokens: 1500

# Automatisierung
automation:
  enable_scheduling: true
  
  schedules:
    full_analysis: "08:00,20:00"  # T채glich um 8:00 und 20:00
    quick_update: "*/2"           # Alle 2 Stunden
    data_backup: "02:00"          # T채glich um 2:00
  
  notifications:
    discord: false
    telegram: false
    email: false

# Sicherheit (Kali Linux Support)
security:
  encryption_enabled: false
  secure_storage: false
  
  # Kali Linux spezifische Einstellungen
  kali_tools:
    use_tor: false
    use_vpn: false
    anonymize_requests: false

# Logging
logging:
  level: "INFO"
  file_rotation: "1 day"
  retention: "30 days"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"

# Performance
performance:
  parallel_requests: 5
  cache_enabled: true
  cache_ttl: 3600  # 1 Stunde
  
  # Memory Management
  max_memory_mb: 1024
  cleanup_temp_files: true

# Visualisierung
visualization:
  enable_plots: true
  plot_style: "seaborn"
  figure_size: [12, 8]
  save_plots: true
  
  # Plotly Dashboard
  dashboard:
    enabled: false
    port: 8050
    host: "127.0.0.1"

# Features
features:
  enable_web_scraping: true
  enable_sentiment_analysis: false
  enable_news_analysis: false
  enable_social_media: false
  
  # Experimentelle Features
  experimental:
    deep_learning: false
    reinforcement_learning: false
    ensemble_methods: true